CREATE TABLE TB_FORNECEDOR (
    CNPJ VARCHAR(15),
    NOME VARCHAR(100),
    ENDERECO1 VARCHAR(150),
    ENDERECO2 VARCHAR(150),
    BAIRRO VARCHAR(50),
    CIDADE VARCHAR(50),
    ESTADO VARCHAR(2),
    CEP VARCHAR(8),
    VOLUME_COMPRA FLOAT
    );