INSERT INTO TABELA_PRODUTO (CODIGO, DESCRICAO, EMBALAGEM, PRECO_UNIDADE) VALUES ('1013793','Clean - 2 Litros - Laranja','PET - 2 Litros',8.00);
INSERT INTO TABELA_PRODUTO (CODIGO, DESCRICAO, EMBALAGEM, PRECO_UNIDADE) VALUES ('1040107','Light - 350 ml - Melância', 'Lata - 350ml', 1.39);

INSERT INTO TABELA_PRODUTO (CODIGO, DESCRICAO, EMBALAGEM, PRECO_UNIDADE) VALUES ('1044567','Frescor do Verão - 350 ml - Limão', 'Lata - 350 ml', 1.39);
INSERT INTO TABELA_PRODUTO (CODIGO, DESCRICAO, EMBALAGEM, PRECO_UNIDADE) VALUES ('1044568','Sabor da Montanha - 700 ml - Uva', 'Garrafa - 700 ml', 11.99);

INSERT INTO TABELA_PRODUTO (CODIGO, DESCRICAO, EMBALAGEM, PRECO_UNIDADE) VALUES ('1045678','Videira do Campo - 1,5 Litros - Melância','PET - 1,5 Litros',6.00);
INSERT INTO TABELA_PRODUTO (CODIGO, DESCRICAO, EMBALAGEM, PRECO_UNIDADE) VALUES ('1078905','Linha Citros - 1 Litro - Limão', 'PET - 1 Litro', 4.29);

INSERT INTO TABELA_PRODUTO (CODIGO, DESCRICAO, EMBALAGEM, PRECO_UNIDADE) VALUES ('544931','Pedaços de Frutas - 350 ml - Maça', 'Lata - 350 ml', 1.39);
INSERT INTO TABELA_PRODUTO (CODIGO, DESCRICAO, EMBALAGEM, PRECO_UNIDADE) VALUES ('1078680','Linha Refrescante - 1 Litro - Morango/Limão,'Garrafa - 1 Litro',4.29);
INSERT INTO TABELA_PRODUTO (CODIGO, DESCRICAO, EMBALAGEM, PRECO_UNIDADE) VALUES ('1042712','Linha Citros - 700 ml - Laranja', 'Garrafa - 700 ml', 11.99);
INSERT INTO TABELA_PRODUTO (CODIGO, DESCRICAO, EMBALAGEM, PRECO_UNIDADE) VALUES ('7889750','Pedaços de Frutas - 1,5 Litros - Pessego','PET - 1,5 Litros', 6.00);

INSERT INTO TABELA_PRODUTO (CODIGO, DESCRICAO, EMBALAGEM, PRECO_UNIDADE) VALUES ('1002767','Sabor da Montanha - 700 ml - Cereja','Garrafa - 700 ml', 11.99);
INSERT INTO TABELA_PRODUTO (CODIGO, DESCRICAO, EMBALAGEM, PRECO_UNIDADE) VALUES ('231776','Sabor da Montanha - 700 ml - Maracuja','Garrafa - 700 ml',11.99);
INSERT INTO TABELA_PRODUTO (CODIGO, DESCRICAO, EMBALAGEM, PRECO_UNIDADE) VALUES ('479745','Linha Citros - 1 Litro - Lima/Limão','Garrafa - 1 Litro',4.29 );
INSERT INTO TABELA_PRODUTO (CODIGO, DESCRICAO, EMBALAGEM, PRECO_UNIDADE) VALUES ('1051518','Linha Refrescante - 700 ml - Manga','Garrafa - 700 ml', 11.99);
INSERT INTO TABELA_PRODUTO (CODIGO, DESCRICAO, EMBALAGEM, PRECO_UNIDADE) VALUES ('1101035','Linha Refrescante - 1 Litro - Manga','PET - 1 Litro',4.29);
INSERT INTO TABELA_PRODUTO (CODIGO, DESCRICAO, EMBALAGEM, PRECO_UNIDADE) VALUES ('229900','Videira do Campo - 350 ml - Melância','Lata - 350 ml',1.39);

INSERT INTO TABELA_PRODUTO (CODIGO, DESCRICAO, EMBALAGEM, PRECO_UNIDADE) VALUES ('1086543','Pedaços de Frutas - 1 Litro - Uva','PET - 1 Litro',4.29);
INSERT INTO TABELA_PRODUTO (CODIGO, DESCRICAO, EMBALAGEM, PRECO_UNIDADE) VALUES ('695594','Festival de Sabores - 1,5 Litros - Açai', 'PET - 1,5 Litros',6.00);
INSERT INTO TABELA_PRODUTO (CODIGO, DESCRICAO, EMBALAGEM, PRECO_UNIDADE) VALUES ('838819','Linha Refrescante - 1,5 Litros - Manga','PET - 1,5 Litros',6.00);
INSERT INTO TABELA_PRODUTO (CODIGO, DESCRICAO, EMBALAGEM, PRECO_UNIDADE) VALUES ('326779','Linha Refrescante - 1,5 Litros - Pera', 'PET - 1,5 Litros',6.00);
INSERT INTO TABELA_PRODUTO (CODIGO, DESCRICAO, EMBALAGEM, PRECO_UNIDADE) VALUES ('520380','Clean - 1 Litro - Laranja','PET - 1 Litro', 4.29);
INSERT INTO TABELA_PRODUTO (CODIGO, DESCRICAO, EMBALAGEM, PRECO_UNIDADE) VALUES ('1041119','Sabor da Montanha - 700 ml - Morango','Garrafa - 700 ml',11.99);
INSERT INTO TABELA_PRODUTO (CODIGO, DESCRICAO, EMBALAGEM, PRECO_UNIDADE) VALUES ('243083','Festival de Sabores - 1,5 Litros - Mirtilo/Morango/Maracujá','PET - 1,5 Litros',6.00);