--RELATÓRIO QUAL PREÇO MÁXIMO DO TOTAL NO ESTOQUE POR EMBALAGEM
SELECT EMBALAGEM, MAX(PRECO_TOTAL) FROM TABELA_ESTOQUE GROUP BY EMBALAGEM;

--RELATÓRIO DE FORNECEDORES ORDENADOS POR ESTADO
SELECT * FROM TABELA_FORNECEDOR ORDER BY ESTADO;

-- RELATÓRIO DE QUANTIDADE DE PRODUTOS POR EMBALAGEM
SELECT EMBALAGEM, COUNT (*) FROM TABELA_PRODUTO GROUP BY EMBALAGEM ORDER BY EMBALAGEM;

--RELATÓRIO DESCRIÇÃO DO PRODUTO COM O CÓDIGO E O CNPJ DO FORNECEDOR
SELECT TABELA_PRODUTO.DESCRICAO, TABELA_PRODUTO.CODIGO, TABELA_ESTOQUE.CNPJ
FROM TABELA_PRODUTO, TABELA_ESTOQUE
WHERE TABELA_PRODUTO.CODIGO = TABELA_ESTOQUE.CODIGO;

-- RELATÓRIO DE VOLUME DE COMPRAS
SELECT CNPJ, NOME, VOLUME_COMPRA FROM TABELA_FORNECEDOR ORDER BY VOLUME_COMPRA DESC;

--RELATORIO DE REPOSIÇÃO DE ESTOQUE
SELECT * FROM TABELA_ESTOQUE WHERE QUANTIDADE<QUANTIDADE_MINIMA;